---

- name: Configuring environment
  lineinfile: >
    dest=/etc/environment
    line='{{ item.name }}="{{ item.value }}"'
  with_items: environment_config
  tags:
    - system
    - environment
    - config
