---

- name: Ensure file exists
  file:
    path: "{{ environment_file }}"
    owner: "{{ environment_file_owner }}"
    group: "{{ environment_file_group }}"
    state: touch
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: Remove previous values
  lineinfile:
    dest: "{{ environment_file }}"
    regexp: '^{{ item.key | upper }}'
    state: absent
  with_dict: "{{ environment_config }}"

- name: Configuring environment
  lineinfile:
    dest: "{{ environment_file }}"
    line: "{{ item.key | upper }}='{{ item.value }}'"
  with_dict: "{{ environment_config }}"
