---

- name: Ensure file exists
  file:
    path: "{{ environment_file }}"
    owner: "{{ environment_file_owner }}"
    group: "{{ environment_file_group }}"
    state: touch
  register: environment_file_result
  changed_when: environment_file_result.diff.before.state != "file"

- name: Configuring environment
  lineinfile:
    dest: "{{ environment_file }}"
    regexp: '^{{ item.key }}'
    line: "{{ item.key }}='{{ item.value }}'"
    state: present
  with_dict: "{{ environment_config }}"
